### ISSUE TITLE
More validations

### ISSUE THREAD

**Issue by Xosmond** [luckyframework/lucky_record#112]
### Currently we only have 
- validate_required
- validate_acceptance_of
- validate_confirmation_of ** Need documentation on the guides
- validate_inclusion_of       ** Need documentation on the guides

### We need:
- [x]  validate_uniqueness_of
- [ ] validate_format_of
- [x] validate_size_of
- validate_numericality_of (still debating best way to handle this)

Do we need an PR for each validation of a complete with all validations PR ?

**Comment by paulcsmith** [comment]
Great suggestion. I think one PR for each would be the best way to handle this. I also think we don't need validate_numericality_of, at least not how it is in Rails. The reason is that each field is parsed by Lucky and if it can't be parsed to the given type it gets an "is invalid" message. So if you have an Int32, you basically get number validation. I think instead `validate_length_of` should be `validate_size_of` and would accept Strings or Int32 | Int64 | Float

```crystal
def validate_size_of(field : Field(String) | AllowedField(String), is expected_size : Int32)
  if field.value.try(&.size) != expected_size
    field.add_error "must be #{expect_size} characters long"
  end
end

def validate_size_of(field : Field(Int32 | Int64 | Float) | AllowedField(Int32 | Int64 | Float), is expected_size : Int32 | Int64 | Float)
  if field.value != expected_size
    field.add_error "must be #{expected_size}"
  end
end
```

validate_uniqueness_of would similarly to Rails where it queries the table. You should still use a unique index of course, but I like how Rails queries the database. When ORMs rely on the database constraint it means you will only get an invalid record when you actually try to insert the record. This leads to a poor user experience when your form has multiple errors, you fix them, submit it, then you get another uniqueness validation later. That's frustrating UX IMO.

Does that all make sense?

**Comment by Xosmond** [comment]
## validate_numericality_of and validate_length_of
I understand your point in `validate_numericality_of` but I think there are other situations where we need that validation, for example:
- Can be used on validating fields that are Strings but they need to be numbers (Example: A Credit Card Number or A Passport Card Number)
- Can be used on validating fields that could be `String` or `Int` with options like:
  - only_integer ** This can't be done with `validate_size_of`
  - odd ** This can't be done with `validate_size_of`
  - even ** This can't be done with `validate_size_of`
  - greater_than
  - greater_than_or_equal_to
  - equal_to
  - less_than
  - less_than_or_equal_to

So I think using the same validation for `String` and `Int` with `validate_size_of` would not be as easy to read as using `validate_numericality_of` and `validate_length_of`

## validate_uniqueness_of
On this we agree, we need to query the database to find if exist another record with the same field, also we can manage:
- scope : field # Managing uniqueness on groups
- case_sensitive : true or false 

These options are easy to apply because we are querying the database.

**Comment by paulcsmith** [comment]
Thanks for the thorough response. I think you're right that combining them would be strange because of all of those options. I still don't think we should have `validate_numericality_of` though because you can also use custom types. So in the credit card number or passport number you could make a custom type and use them like this:

```crystal
field credit_card_number : CreditCardNumber # This could would delete spaces and dashes and check that it's an int and the right length
field passport_number : PassportNumber 
```

So this is what I propose:

## validate_size_of for strings (or anything that responds to `size`)

* is
* min
* max


```crystal
validate_size_of title, min: 10
```

## validate_number for Ints and Floats

* is
* greater_than
* greater_than_or_equal_to
* less_than
* less_than_or_equal_to
* odd - just for ints
* even - just for ints

```crystal
# This this won't parse strings to int. It must already be an int or float type field
validate_number age, greater_than: 0, less_than: 130
```

**Comment by Xosmond** [comment]
I have to say that this is the first time I read about custom types and they look really powerful, cleaner and help to caught errors soon.

I will read about it and try them out. I will try to make a PR later.

**Comment by paulcsmith** [comment]
Instead of validate_form_of, I'll document custom types. I think that's the best way to go for now
