### ISSUE TITLE
Preloading doesn't work when multiple associations reference the same model class

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_record#290]
```
table :transaction do
  belongs_to buyer : User
  belongs_to seller : User
end
```

It only preloads *one* of them. See 
https://gitter.im/luckyframework/Lobby?at=5bb77d3882893a2f3ba410fd

## Fix

https://github.com/luckyframework/lucky_record/issues/290#issuecomment-451337996

Change [`preload`](
https://github.com/luckyframework/lucky_record/blob/192b99827f7ca393d9f2312c229eb0c809a8f4d7/src/lucky_record/associations.cr#L137) to `preload_{{ assoc_name }}`

**Comment by bcardiff** [comment]
FYI we reach this bug today and found that the culprit is that `BaseQuery#preload` defined at https://github.com/luckyframework/lucky_record/blob/192b99827f7ca393d9f2312c229eb0c809a8f4d7/src/lucky_record/associations.cr#L137 is redefined on each belongs_to invocation.

I am not sure if the `BaseQuery#preload` is aim for public api, but if not defining it as `BaseQuery#preload_{{ assoc_name }}` seems to be enough.

**Comment by paulcsmith** [comment]
Thank you so much for investigating! It is not meant to be a public API so that should work. If you could submit a PR that would be great, but if not I’ll try to tackle that after the new year!
