### ISSUE TITLE
Add way to use raw WHERE query

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_record#56]
So that if there is something not implemented by LuckyRecord, user's can still do what they need to do when joining, using OR, etc.

Something like:

```crystal
UserQuery.new.raw_where("users.name = #{PG::EscapeHelper.escape_literal("Paul")}") 
```

This would likely be done by adding a `@raw_where = [] of String` to `QueryBuilder` that gets joined to the regular where clauses. Then adding a `raw_where` method to `Queryable`

### Note

It will be helpful to add something to the guides that explains this AND explains how to generate a 100% custom query and parse with Lucky::Repo and DB.mapping. That's something that shouldn't require any code changes in LuckyRecord though.

**Comment by edwardloveall** [comment]
I've been thinking about this a lot and I've come up with a bunch of ways to do this. Maybe you had something in mind already or maybe I'm missing the elegant solution.

1. We could give devs direct access to the DB so they could do something like

```crystal
LuckyRecord::DB.exec("SELECT * FROM users")
```

They then get back a `DB::ResultSet` and have to loop through it and extract out the variables, which puts a lot of work onto them. This is kind of what Rails does with `ActiveRecord::Base.connection.execute`. It returns a `PG::Result` enumerable where each result is a Hash.

2. We could implement our own mapping that returns each result as a hash. It's not insane (I think) for us to do and would give developers the stopgap they need to get things done. Although I'd hate to see it catch on and have it turn into the default way.

3. We could instead allow devs to pass directly into `User.from_rs(database.query(...))`. The problem there is they have to be explicit about what they are selecting. I.E. `SELECT users.id, users.created_at, ...` etc otherwise there's a mapping error especially for the cases you outlined (joins and case statements).

4. We could also have them create their own temporary model class for whatever they needed:

```crystal
class UserCount
  DB.mapping({
    count: Int64
  })
end

user_count = UserCount.from_rs(
  LuckyRecord::DB.exec("SELECT COUNT(*) FROM users")
)
```

Of these four, I like one and four the best. They are on opposite ends of the spectrum from totally raw to highly controlled. I like one because it encourages devs to use the nice framework within LukcyRecord, while still allowing them to get work done. I like four because it lets them be safe and explicit with their results, even if it's a bit tedious.

Two and three seem hacky for both parties, but they aren't totally terrible. They just aren't great options I think.

**Comment by edwardloveall** [comment]
I think this would have the same problems that 3 has above. When you join a new table (or have any other attributes that are not in the model) it raises a `DB::MappingException`.

```sql
SELECT * FROM users JOIN posts ON users.id = posts.user_id;

-- returns users.id, users.name, posts.id, posts.user_id, posts.title, posts.body
```

This will try to map all the fields from `users` and all the fields from `posts`. The post fields don't have mappings and then the exception is raised. (I imagine you know this but I wanted to type it all out for posterity or anyone else reading who might not know 🙂).

I could see solving this by:

* Explicitly adding the model fields in the select statement (`SELECT users.id, users.name FROM users`) and
* Ensuring that whatever SQL passed is after SELECT

I suppose we could have devs specify mapping somehow for any extra fields? Thinking about it quickly I can't think of a clean way to insert more mappings? Maybe it's easier than I think.

Also, to be clear, this would always try to return whatever model it was called on, right? `User.where("name = lower(?)", "my name")` would return an Array(User).

**Comment by paulcsmith** [comment]
Ah, yes. That makes sense. Thank you for documenting that. I think that this would require https://github.com/luckyframework/record/issues/90. I want to make it so it only selects the field the model defines. This has the side benefit of being able to declare different models with different fields for the same table.

```crystal
class Users
  table users do
    # just fields that a user needs
  end
end

class Admin
  table users do
    # just fields that an admin needs
  end
end
```

And yeah that last example should still return an `Array(User)`.

**Comment by edwardloveall** [comment]
Cool, that makes sense. It'll still raise errors when devs try to do aggregate functions (which we'll add) or things like cases. But I think 1 above would be a good option to provide for those edge cases/library authors.

**Comment by paulcsmith** [comment]
Yeah I agree. I think a custom mapping makes sense in those cases. And the aggregate functions will also bypass the regular mapping and read the result as an Int I think. BTW thanks for your writeup. You write very clearly. I really appreciate that and I bet others will too when they read this later on to see how decisions were made 👍

**Comment by edwardloveall** [comment]
You're welcome 🙂. I'm always thinking about these as historical documents. It's frustrating when people just say "It won't work".

**Comment by paulcsmith** [comment]
@mikeeus would you be interested in this one?

**Comment by mikeeus** [comment]
Sure, this looks pretty interesting. Thanks for the write up @edwardloveall.

From what I gathered, we're taking about two separate points here.
1. Allow users to run raw `where` queries.
2. Allow users to run raw queries including `SELECT` and `JOIN` statements, which might break mapping.

Regarding 1: this should be straight forward since it doesn't effect the statement and break the mapping. But it might need to check for statements like `SELECT` and `JOIN` to make sure it isn't abused, right? If this is correct, then I'll make PR for it.

Regarding 2: I agree with the discussion that having options 1 and 4 would be useful. Isn't `LuckyRecord::Repo.db` already exposed to the user so both options are ready.

Also I could see a flow like:
```crystal
class UserCount < LuckyRecord::CustomQuery
  mapping({
    count: Int32
  })
end
```
Where `LuckyRecord::CustomQuery` provides a `mapping` method that uses `DB::mapping` under the hood. This way it doesn't expose `DB` directly and we can extend it in the future. Possibly with `join(class : LuckyRecord::Model | LuckyRecord::CustomQuery)` or something similar.

**Comment by paulcsmith** [comment]
Great questions. I'm glad you asked. I think for now let's just do item 1, raw where clauses. I don’t think we need to check for select and join yet. 

For totally custom queries using selects and joins, etc. I think we can add guides for it because you’re right that you can do that yourself. 

In the future, we may add support for using custom selects and custom mapping’s that is easier to use. But for now using Repo directly should be fine for those rarer cases. 

Does that answer your question? @mikeeus

**Comment by mikeeus** [comment]
Yeah that answers it, thanks
